# Generated by Django 6.0.2 on 2026-04-06 21:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compte', '0001_initial'),
        ('hopital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_don', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('valide', models.BooleanField(default=False)),
                ('donateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.donneur')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.hopital')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseAppel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reponse', models.DateField(default=datetime.date.today)),
                ('statut', models.CharField(choices=[('accepte', 'Accepté'), ('refuse', 'Refusé')], default='accepte', max_length=20)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital.demandeurgente')),
                ('donateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.donneur')),
            ],
        ),
    ]
