# Generated by Django 6.0.2 on 2026-04-06 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeUrgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(max_length=5)),
                ('quantite', models.PositiveIntegerField()),
                ('delai', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('description', models.TextField(default='')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.hopital')),
            ],
        ),
    ]
