# Generated by Django 4.2.28 on 2026-05-14 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dondesong', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='creneau_horaire',
        ),
        migrations.AddField(
            model_name='donneur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='groupes_cibles',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dondesong.hopital'),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='lieu',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='demandeurgente',
            name='groupe_sanguin',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='demandeurgente',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dondesong.hopital'),
        ),
        migrations.AlterField(
            model_name='demandeurgente',
            name='statut',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='don',
            name='donneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dondesong.donneur'),
        ),
        migrations.AlterField(
            model_name='don',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dondesong.hopital'),
        ),
        migrations.AlterField(
            model_name='don',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='don',
            name='valide',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='groupe_sanguin',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='ville',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='agrement',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='ville',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='campagne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dondesong.campagne'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='donneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dondesong.donneur'),
        ),
        migrations.AlterField(
            model_name='reponseappel',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dondesong.demandeurgente'),
        ),
        migrations.AlterField(
            model_name='reponseappel',
            name='donneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dondesong.donneur'),
        ),
        migrations.AlterField(
            model_name='reponseappel',
            name='statut',
            field=models.CharField(choices=[('intention', 'Intention'), ('effectue', 'Effectué')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='reponseappel',
            unique_together={('demande', 'donneur')},
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('capacite', models.IntegerField()),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dondesong.campagne')),
            ],
        ),
        migrations.AddField(
            model_name='inscription',
            name='creneau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dondesong.creneau'),
        ),
    ]
