# Generated by Django 4.2.28 on 2026-05-16 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dondesong', '0002_remove_inscription_creneau_horaire_donneur_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopital',
            name='agrement',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='ville',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
