# Generated by Django 6.0.2 on 2026-04-06 21:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('date', models.DateField(default=datetime.date.today)),
                ('lieu', models.CharField(max_length=150)),
                ('groupes_cibles', models.CharField(max_length=100)),
                ('capacite_totale', models.PositiveIntegerField()),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.hopital')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creneau_horaire', models.TimeField()),
                ('date_inscription', models.DateField(default=datetime.date.today)),
                ('present', models.BooleanField(default=False)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compagnes.campagne')),
                ('donateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.donneur')),
            ],
        ),
    ]
